Fix file transfer for collected electrons
AgnostiqHQ/covalent pull request #1190
Opened 2022-09-08 15:35 UTC by FyzHsn

Fixes #1179 

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2022-09-08 16:06 UTC, cjao requested changes

2022-09-08 16:06 UTC, cjao commented on covalent/_workflow/electron.py
> +                iterable_metadata[
Hi @FyzHsn, unfortunately this approach is a bit too blunt. For example, what would happen if a pip dep is needed to interpret the inputs to `get_item`? See #1191.

2022-09-09 13:12 UTC, cjao approved these changes
As discussed yesterday, this hack does fix the immediate problem, but we should filter out all file transfers in these auto-generated electrons in the near future (see #1191).

2022-09-09 13:32 UTC, kessler-frost commented
Hmm, I'm a bit concerned and confused. If the problem is with a `generator` electron, then why is it even executed? And if it isn't executed then how does its metadata matter? Shouldn't it be only handled in post processing?

2022-09-09 13:37 UTC, cjao commented
Generator electrons work a bit differently from before. The unpacking happens in an executor because the dispatcher would generically not have the dependencies to unpack an encoded collection. This is analogous to how collection-type electrons work now.

2022-09-09 13:38 UTC, kessler-frost commented
I see, so does that mean these electrons will also get executed in a separate executor? (If yes, then we definitely need to change that).

2022-09-09 13:41 UTC, kessler-frost commented
Whew, ok, so @FyzHsn I would say the problem is a lot more fundamental than I thought it was. I assume that is what you were trying to convey earlier.

2022-09-09 13:42 UTC, kessler-frost commented
>The unpacking uses the same executor as the main electron. That is guaranteed to work because the main electron's executor will have the dependencies to generate the collection that needs to be unpacked.

Yeah, but that means it'll occupy a huge amount of resource to do an extremely trivial thing which theoretically can be handed off to the electron which actually needs it.

2022-09-09 13:45 UTC, kessler-frost commented
Another solution might be to add tags to the `TransportableObject` which will help in filtering these things out on the destination electron's remote machine itself.

2022-09-09 13:45 UTC, cjao commented
> > The unpacking uses the same executor as the main electron. That is guaranteed to work because the main electron's executor will have the dependencies to generate the collection that needs to be unpacked.
> 
> Yeah, but that means it'll occupy a huge amount of resource to do an extremely trivial thing which theoretically can be handed off to the electron which actually needs it.

Postprocessing and the collection-type electrons have the same problem. Ideally we could just reserve the main electron's executor until the auxiliary tasks have finished. The planned [executor-sharing](https://github.com/AgnostiqHQ/covalent/discussions/943#) feature could help.

2022-09-12 13:48 UTC, cjao submitted a review, later dismissed
Looks good! Followup discussion in #1196 .

2022-09-12 15:22 UTC, kessler-frost approved these changes

2022-09-12 15:41 UTC, cjao approved these changes

2022-09-12 15:43 UTC, merged