Fix benchmark workflow
AgnostiqHQ/covalent pull request #1245
Opened 2022-09-15 14:12 UTC by venkatBala

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2022-09-15 19:34 UTC, scottwn requested changes

2022-09-15 19:34 UTC, scottwn commented on .github/workflows/release.yml
> +          && github.event_name != 'schedule'
this is unnecessary, we're already checking that the `event_name` is `workflow_dispatch`

2022-09-17 04:08 UTC, wjcunningham7 submitted a review, later dismissed

2022-09-17 14:03 UTC, scottwn approved these changes

2022-09-18 03:16 UTC, merged