fix default directory paths
AgnostiqHQ/covalent pull request #1439
Opened 2022-12-06 17:55 UTC by venkatBala

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

Updating the default paths to `directory` like environment variables to avoid creating re-dundant directories when self-hosting

2022-12-06 21:01 UTC, AlejandroEsquivel requested changes

2022-12-09 22:29 UTC, venkatBala commented on covalent/_shared_files/defaults.py
> +        or ((os.environ.get("XDG_CACHE_HOME") or (os.environ["HOME"] + "/.cache/covalent"))),
@AlejandroEsquivel `XDG_CACHE_HOME` is intended to be a full path like `COVALENT_LOGDIR` so appending `/.cache/covalent` would be redundant

2022-12-09 23:35 UTC, AlejandroEsquivel commented on covalent/_shared_files/defaults.py
> +        or ((os.environ.get("XDG_CACHE_HOME") or (os.environ["HOME"] + "/.cache/covalent"))),
got it 👍🏼

2022-12-09 23:35 UTC, AlejandroEsquivel approved these changes
Looks good thanks @venkatBala  👍🏼

2022-12-09 23:35 UTC, merged