Improving `get_result` for remote servers
AgnostiqHQ/covalent pull request #1460
Opened 2023-01-06 04:53 UTC by kessler-frost

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

Resolves #1457

2023-01-11 15:23 UTC, venkatBala requested changes

2023-01-11 16:05 UTC, wjcunningham7 commented on covalent/_results_manager/results_manager.py
>      import shutil
This method is entirely broken -- it needs to be an API call with no references to the local filesystem

2023-01-11 16:13 UTC, cjao commented on covalent/_results_manager/results_manager.py
>      import shutil
We're still using this in [functional tests](https://github.com/AgnostiqHQ/covalent/blob/691cf4ebe5e3590097a540ef4ddd50e97cbaaf94/tests/functional_tests/workflow_stack_test.py). But it really belongs a server-side storage management module.

2023-01-11 16:13 UTC, kessler-frost commented on covalent/_results_manager/results_manager.py
>      import shutil
Ah, my bad that is true. I meant to say anywhere user facing.

2023-01-13 22:16 UTC, FyzHsn submitted a review, later dismissed

2023-01-13 22:18 UTC, FyzHsn submitted a review, later dismissed

2023-01-15 00:09 UTC, venkatBala approved these changes

2023-01-15 00:25 UTC, venkatBala approved these changes

2023-01-16 15:20 UTC, FyzHsn approved these changes

2023-01-16 15:25 UTC, venkatBala submitted a review, later dismissed

2023-01-16 19:34 UTC, FyzHsn approved these changes

2023-01-16 19:34 UTC, merged