Doc UI ref - fix links
AgnostiqHQ/covalent pull request #1476
Opened 2023-01-16 05:23 UTC by dwelsch-esi

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2023-01-16 15:05 UTC, santoshkumarradha approved these changes

2023-01-16 15:05 UTC, santoshkumarradha submitted a review, later dismissed

2023-01-17 01:42 UTC, santoshkumarradha approved these changes

2023-01-17 11:24 UTC, wjcunningham7 requested changes

2023-01-17 11:24 UTC, wjcunningham7 commented on README.md
> +  - [What is covalent?](https://www.covalent.xyz/what-is-covalent/)
```suggestion
  - [What is Covalent?](https://www.covalent.xyz/what-is-covalent/)
```

2023-01-17 11:24 UTC, wjcunningham7 commented on README.md
> +  - [How does covalent work?](#how-does-it-work)
```suggestion
  - [How does Covalent work?](#how-does-it-work)
```

2023-01-17 18:21 UTC, wjcunningham7 approved these changes

2023-01-17 18:55 UTC, santoshkumarradha approved these changes

2023-01-17 18:59 UTC, merged