Implementing Covalent re-dispatch functionality
AgnostiqHQ/covalent pull request #1493
Opened 2023-01-23 16:31 UTC by FyzHsn

Fixes #1475 

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2023-01-25 18:49 UTC, kessler-frost requested changes

2023-01-25 18:49 UTC, kessler-frost commented on covalent/_workflow/electron.py
> +from .._shared_files.context_managers import active_dispatch_info_manager, active_lattice_manager
If we're going to use `active_dispatch_info_manager` even for a short while, let's rename it to something more relevant to what it's doing.

2023-01-25 18:49 UTC, kessler-frost commented on tests/covalent_tests/dispatcher_plugins/redispatch_utils_test.py
> +        new_args=[1, 2],
Can you also add new kwargs here?

2023-01-27 00:39 UTC, kessler-frost approved these changes

2023-01-27 02:31 UTC, AlejandroEsquivel approved these changes
Looks great @FyzHsn !

2023-01-27 02:31 UTC, merged