Transport graph diff functionality
AgnostiqHQ/covalent pull request #1502
Opened 2023-01-30 14:52 UTC by FyzHsn

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2023-02-01 22:02 UTC, FyzHsn commented on covalent_dispatcher/_db/load.py
> +def _result_from(lattice_record: Lattice) -> Result:
Tests for this will be added in the future!

2023-02-01 22:02 UTC, FyzHsn commented on covalent_dispatcher/_db/load.py
> +def get_result_object_from_storage(
Tests for this will be added in the future.

2023-02-01 22:20 UTC, kessler-frost requested changes

2023-02-01 22:20 UTC, kessler-frost commented on covalent/_workflow/transport.py
> +        self.set_node_value(node_id, "start_time", None)
You can probably use a list of strings here then iterate over it since most of them are being set to `None` and handle `status` outside of the loop.

2023-02-01 22:20 UTC, kessler-frost commented on covalent_dispatcher/_db/load.py
> +    pass
Are these supposed to be empty?

2023-02-01 22:20 UTC, kessler-frost commented on tests/covalent_tests/workflow/transport_graph_ops_test.py
> +
These tests look 💯 ⭐ !

2023-02-01 22:20 UTC, kessler-frost commented on tests/covalent_tests/workflow/transport_test.py
> +        call(node_id, "stderr", None),
Here as well, just use a for loop instead.

2023-02-01 22:21 UTC, kessler-frost commented on covalent/_workflow/transport.py
> +        self.set_node_value(node_id, "stderr", None)
You can probably use a list of strings here then iterate over it since most of them are being set to `None` and handle `status` outside of the loop.

2023-02-01 22:23 UTC, kessler-frost commented on covalent_dispatcher/_db/load.py
> +    pass
Saw you comment now @FyzHsn , I'm assuming the answer is yes.

2023-02-02 14:47 UTC, kessler-frost approved these changes

2023-02-02 14:48 UTC, merged