Re-introduction: Implement dispatch cancellation (#1495)
AgnostiqHQ/covalent pull request #1527
Opened 2023-02-15 19:17 UTC by AlejandroEsquivel

This reverts commit a7a8987d459b8fe8d5597ef930236cce499e6264.

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2023-02-15 19:57 UTC, FyzHsn requested changes

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    def get_cancel_requested(self):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    def set_job_handle(self, handle):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +            self._notify("bye")
Are we sure we want "bye" here?

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    def cancel(self, task_metadata: Dict, job_handle: Any):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    async def _cancel(self, task_metadata: Dict, job_handle: Any):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    def _init_runtime(
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    def _notify(self, action: str, body: Any = None):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    async def _notify_sync(self, action: str, body: Any = None):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    async def _wait_for_response(self, timeout: int = 5):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    async def get_cancel_requested(self):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    async def set_job_handle(self, handle):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    async def cancel(self, task_metadata: Dict, job_handle: Any):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/base.py
> +    async def _cancel(self, task_metadata: Dict, job_handle: Any):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/executor_plugins/dask.py
> +    async def cancel(self, task_metadata: Dict, job_handle):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent/executor/executor_plugins/local.py
> +        self.set_job_handle(42)
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/data_modules/job_manager.py
> +def _set_cancel_requested(job_ids: List[int]) -> None:
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/data_modules/job_manager.py
> +async def set_cancel_requested(dispatch_id: str, task_ids: List[int]):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/data_modules/job_manager.py
> +async def get_jobs_metadata(dispatch_id: str, task_ids: List[int]) -> List:
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/data_modules/job_manager.py
> +async def _set_job_metadata(dispatch_id: str, task_id: int, **kwargs):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/data_modules/job_manager.py
> +async def set_job_handle(dispatch_id: str, task_id: int, job_handle: str):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/data_modules/job_manager.py
> +async def set_cancel_result(dispatch_id: str, task_id: int, cancel_status: bool):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/dispatcher.py
> +async def cancel_dispatch(dispatch_id: str, task_ids: List[int] = []):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/runner.py
> +async def _cancel_task(dispatch_id, task_id: int, executor, executor_data: Dict, job_handle: str):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/runner.py
> +async def cancel_tasks(dispatch_id: str, task_ids: List[int]):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/runner.py
> +    def to_cancel_kwargs(i, node_id):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/runner.py
> +def _get_metadata_for_nodes(dispatch_id: str, node_ids: list):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/runner.py
> +async def _get_cancel_requested(dispatch_id: str, task_id: int):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/runner_modules/executor_proxy.py
> +async def _get_cancel_requested(dispatch_id: str, task_id: int):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/runner_modules/executor_proxy.py
> +async def _put_job_handle(dispatch_id: str, task_id: int, job_handle: str):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/runner_modules/executor_proxy.py
> +async def _handle_message(
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_core/runner_modules/executor_proxy.py
> +async def watch(dispatch_id: str, task_id: int, executor: _ABE):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/jobdb.py
> +class MissingJobRecordError(Exception):
Add docstring.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/jobdb.py
> +def txn_get_job_record(session: Session, job_id: int) -> Dict:
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/jobdb.py
> +def _update_job_record(
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/jobdb.py
> +def get_job_record(job_id: int) -> Dict:
Add docstring.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/jobdb.py
> +def update_job_records(record_kwargs_list: list):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/jobdb.py
> +def get_job_records(job_ids: List[int]) -> Dict:
Add docstring.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/upsert.py
> +def _lattice_data(session: Session, result: Result, electron_id: int = None):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/upsert.py
> +def _electron_data(session: Session, result: Result, cancel_requested: bool = False):
Add docstring args, return and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/upsert.py
> +        try:
(non blocking + nit pick) Can this be moved into a loop?

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/upsert.py
> +def lattice_data(result: Result, electron_id: int = None):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/upsert.py
> +def electron_data(result: Result, cancel_requested: bool = False):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/upsert.py
> +def persist_result(result: Result, electron_id: int = None):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/write_result_to_db.py
> +def txn_insert_lattices_data(
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/write_result_to_db.py
> +def insert_lattices_data(*args, **kwargs):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/write_result_to_db.py
> +def txn_insert_electrons_data(
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/write_result_to_db.py
> +def insert_electrons_data(*args, **kwargs):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/write_result_to_db.py
> +def txn_insert_electron_dependency_data(session: Session, dispatch_id: str, lattice: LatticeClass):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/write_result_to_db.py
> +def insert_electron_dependency_data(*args, **kwargs):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/write_result_to_db.py
> +def txn_upsert_electron_dependency_data(session: Session, dispatch_id: str, lattice: LatticeClass):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/write_result_to_db.py
> +def txn_update_lattices_data(session: Session, dispatch_id: str, **kwargs) -> None:
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_db/write_result_to_db.py
> +def update_lattices_data(dispatch_id: str, **kwargs) -> None:
Enhance docstrings to add args sections

2023-02-15 19:57 UTC, FyzHsn commented on covalent_dispatcher/_service/app.py
> +def _result_from(lattice_record: Lattice) -> Result:
This does not belong here.

2023-02-15 19:57 UTC, FyzHsn commented on tests/covalent_dispatcher_tests/_core/data_modules/job_manager_test.py
> +
Add a one liner doc string for each of the tests.

2023-02-15 19:57 UTC, FyzHsn commented on tests/covalent_dispatcher_tests/_core/dispatcher_test.py
> +@pytest.mark.asyncio
Add a one liner doc string for each of the tests.

2023-02-15 19:57 UTC, FyzHsn commented on tests/covalent_dispatcher_tests/_core/runner_test.py
> +async def test__cancel_task(mocker):
one liner doc string.

2023-02-15 19:57 UTC, FyzHsn commented on tests/covalent_dispatcher_tests/_db/jobdb_test.py
> +def test_get_job_record(test_db, mocker):
One liner docstring for each test.

2023-02-15 19:57 UTC, FyzHsn commented on tests/covalent_dispatcher_tests/_service/app_test.py
> +def test_cancel_dispatch(mocker, app, client):
One liner doc string.

2023-02-15 19:57 UTC, FyzHsn commented on tests/covalent_tests/executor/base_test.py
> +def test_base_executor_get_cancel_requested(mocker):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on tests/covalent_tests/executor/executor_plugins/dask_test.py
> +def test_dask_executor_run_cancel_requested(mocker):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on tests/covalent_tests/executor/executor_plugins/local_test.py
> +def test_local_executor_get_cancel_requested(mocker):
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on tests/functional_tests/workflow_cancellation_test.py
> +def test_cancel():
Add docstring and return type in function definition.

2023-02-15 19:57 UTC, FyzHsn commented on tests/functional_tests/workflow_cancellation_test.py
> +def test_cancel_sublattice():
Add docstring and return type in function definition.

2023-02-15 21:02 UTC, AlejandroEsquivel commented on covalent_dispatcher/_service/app.py
> -    except Exception as e:
this as well

2023-02-16 17:20 UTC, cjao approved these changes

2023-02-16 17:22 UTC, FyzHsn requested changes
Great work on addressing all these changes so quickly. There are some missing input parameters and return types that need to be added, sir!

2023-02-16 17:22 UTC, FyzHsn commented on covalent/executor/base.py
> +    async def set_job_handle(self, handle):
Needs a return type in the function signature

2023-02-16 17:22 UTC, FyzHsn commented on covalent/executor/base.py
> +    async def _cancel(self, task_metadata: Dict, job_handle: Any):
Needs a return type in the function signature

2023-02-16 17:22 UTC, FyzHsn commented on covalent_dispatcher/_core/runner.py
> +async def _get_cancel_requested(dispatch_id: str, task_id: int):
Needs a return type in the function signature

2023-02-16 17:22 UTC, FyzHsn commented on covalent/executor/base.py
> +    def set_job_handle(self, handle):
needs type for handle.

2023-02-16 18:08 UTC, venkatBala commented on covalent_migrations/versions/f64ecaa040d5_add_jobs_db_table.py
> +import sqlalchemy as sa
@FyzHsn yup... the functional tests passing is an assertion that the db migrations are working

2023-02-16 18:48 UTC, FyzHsn approved these changes

2023-02-16 18:48 UTC, FyzHsn commented on covalent_dispatcher/_core/data_modules/job_manager.py
> +async def get_jobs_metadata(dispatch_id: str, task_ids: List[int]):
```suggestion
async def get_jobs_metadata(dispatch_id: str, task_ids: List[int]) -> Any:
```

2023-02-16 18:49 UTC, FyzHsn submitted a review, later dismissed

2023-02-16 18:55 UTC, FyzHsn approved these changes

2023-02-16 19:12 UTC, cjao approved these changes

2023-02-16 19:13 UTC, merged