OS Dispatcher refactor - workflow dispatch
AgnostiqHQ/covalent pull request #153
Opened 2022-03-03 19:20 UTC by FyzHsn

Fixes #150

2022-03-10 21:55 UTC, kessler-frost requested changes
It seems there is duplication of code. There's a `dispatch_workflow_v2.py` and `dispatch_workflow.py`, we only need the latter maybe you can merge them?

2022-03-10 21:55 UTC, kessler-frost commented on refactor/dispatcher/app/api/api_v0/endpoints/workflow.py
> +
Can you remove the underscores from these functions?

2022-03-11 20:26 UTC, scottwn submitted a review, later dismissed

2022-03-11 20:27 UTC, kessler-frost approved these changes

2022-03-11 20:54 UTC, merged