dispatch when covalent server is not available
AgnostiqHQ/covalent pull request #1601
Opened 2023-04-25 22:00 UTC by madhur-tandon

Fixes https://github.com/AgnostiqHQ/covalent/issues/1260

- [x] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

2023-04-25 22:06 UTC, madhur-tandon commented
This should be ready to merge as well, @santoshkumarradha @kessler-frost @AlejandroEsquivel

2023-04-28 09:31 UTC, kessler-frost commented
@madhur-tandon Again, thanks for the PR! Seems like the diff coverage isn't >=95%. These two lines (line 149, 150) in `covalent/_dispatcher_plugins/local.py` seem to be the culprit here:

```python
                r.raise_for_status()
                lattice_dispatch_id = r.content.decode("utf-8").strip().replace('"', "")
```

Once these are covered as well, i.e taking care of the `try` block, the diff coverage should be sufficient for passing the check.

2023-04-28 09:31 UTC, kessler-frost requested changes

2023-04-28 09:31 UTC, kessler-frost commented on covalent/_dispatcher_plugins/local.py
> +                lattice_dispatch_id = r.content.decode("utf-8").strip().replace('"', "")
Tests for these.

2023-04-28 10:15 UTC, madhur-tandon commented on covalent/_dispatcher_plugins/local.py
> +                lattice_dispatch_id = r.content.decode("utf-8").strip().replace('"', "")
should be done now!

2023-04-28 10:22 UTC, madhur-tandon commented
@kessler-frost last commit is to make `license/cla` work

2023-04-28 10:30 UTC, madhur-tandon commented
Feel free to merge @kessler-frost!

2023-04-28 10:32 UTC, kessler-frost approved these changes

2023-04-28 10:32 UTC, merged