updating license on develop
AgnostiqHQ/covalent pull request #1784
Opened 2023-09-21 16:36 UTC by wjcunningham7

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2023-09-21 17:07 UTC, kessler-frost commented on .github/workflows/boilerplate.yml
Do we want to remove the this workflow completely?

2023-09-21 17:12 UTC, kessler-frost requested changes
Pretty much everything looks good, just one comment about the `boilerplate.yml` workflow. I don't think its a good idea to get rid of it, I have a suspicion that its removal was accidental 😶 .

2023-09-21 17:13 UTC, kessler-frost commented
Also, the changelog needs to be updated.

2023-09-21 20:37 UTC, Andrew-S-Rosen commented
Closes #1745.

Thank you so much!!! 🙏

2023-09-23 00:00 UTC, kessler-frost approved these changes

2023-09-23 00:45 UTC, merged