Relax the strict version pins for lmdbm, mpire, orjson, and pennylane
AgnostiqHQ/covalent pull request #1795
Opened 2023-09-28 18:20 UTC by Andrew-S-Rosen

This is a test to see if removing the version pin on `orjson` breaks things (also testing the others added in #1794).

Edit: anddddd success 🙏

- [X] I have added the tests to cover my changes.
- [X] I have updated the documentation and CHANGELOG accordingly.
- [X] I have read the CONTRIBUTING document.

2023-09-28 18:51 UTC, Andrew-S-Rosen commented
@kessler-frost: Looks like this passed. I'm going to update the CHANGELOG. Feel free to propose any changes from here.

2023-10-02 16:41 UTC, kessler-frost requested changes
Thanks @Andrew-S-Rosen ! Just a minor comment.

2023-10-02 16:41 UTC, kessler-frost commented on CHANGELOG.md
> +- Remove version pin on `lmdbm`, `mpire`, `orjson`, and `pennylane`
Might wanna move this to the `Changed` section.

2023-10-02 21:03 UTC, Andrew-S-Rosen commented
@kessler-frost: Thanks! I agree about the CHANGELOG category change. All fixed!

2023-10-03 23:22 UTC, kessler-frost approved these changes

2023-10-03 23:24 UTC, merged