fixes #1783
AgnostiqHQ/covalent pull request #1810
Opened 2023-10-12 12:50 UTC by AdityaRaj23

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2023-10-12 12:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AgnostiqHQ/covalent?pullRequest=1810) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AgnostiqHQ/covalent?pullRequest=1810) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AgnostiqHQ/covalent?pullRequest=1810) it.</sub>

2023-10-12 21:50 UTC, kessler-frost commented
Hey @AdityaRaj23! Thanks for this, you might wanna update the CHANGELOG.md file briefly explaining what did you change under the appropriate section, which for this one is the "Fixed" section, also can you remove the yarn.lock change that was pushed in this one as well. Let me know if you need any help anywhere.

2023-10-13 06:41 UTC, AdityaRaj23 commented
should i leave the code i changed commented or remove it before making another pull request?

2023-10-13 06:45 UTC, kessler-frost commented
You don't have to make another pull request, you can just commit and push to this branch itself and it'll be updated here.

2023-10-13 11:41 UTC, kessler-frost commented
@AdityaRaj23 , it seems like you have deleted the `yarn.lock` file which isn't what I quite meant, I meant that it shouldn't be different than what it currently is in our `develop` branch.

One tip for the commit messages is that they should be a bit more informative as to what was done in that particular commit. Making only one commit with `fixed AgnostiqHQ#1783` is sufficient to connect this PR to the 1783 issue.

2023-10-13 14:32 UTC, AdityaRaj23 commented
Sorry, I read the contributing.md there it was written ,for fixing you should commit with message 'fixes#{issue no}' so i stick to that but will surely keep this in my mind from now onwards for any commit

2023-10-13 17:25 UTC, kessler-frost requested changes

2023-10-13 17:25 UTC, kessler-frost commented on CHANGELOG.md
> +- changed code at line 218 in covalent/_shared_files/utils.py
This needs to be near the top of the file under the `[UNRELEASED]` heading. You might see there's already a `Fixed` section within which you can add these.

2023-10-13 17:25 UTC, kessler-frost commented on covalent_ui/webapp/yarn.lock
You seem to have deleted this file, copying this file from `develop` to your branch to its respective place and pushing again will make sure this hasn't been modified unnecessarily.

2023-10-16 14:02 UTC, kessler-frost commented
Hey @AdityaRaj23 , seems like the test coverage isn't up to the mark with what is expected, so you'll need to add a test for the changes that you made. This will also make sure that the thing that you fixed will not be broken by any of the later commits by anyone else.

So, the file where you'll wanna add the change is `tests/covalent_tests/shared_files/utils_test.py`, and the function that needs to be tested is `get_named_params`. A simpler way to reproduce the same error above is:
```python
from covalent._shared_files.utils import get_named_params

def test_func(a, *, b):
    return a + b

named_args, named_kwargs = get_named_params(test_func, [1], {'b': 2})
```
So, you essentially just need to test that this isn't failing and then the PR should be gtg.

2023-10-16 14:06 UTC, AdityaRaj23 commented
Ok will do as directed

2023-10-30 15:51 UTC, kessler-frost commented
Hey @AdityaRaj23 just bumping this one. You're almost there and I think it would be a shame if this didn't get merged for Hacktoberfest as this is pretty much done. You just need to put the test that you wrote in a function and that would be it.

2023-10-30 22:35 UTC, AdityaRaj23 commented
> Hey @AdityaRaj23 just bumping this one. You're almost there and I think it would be a shame if this didn't get merged for Hacktoberfest as this is pretty much done. You just need to put the test that you wrote in a function and that would be it.

I would do that today positively was busy in some other work ...

2023-10-31 16:30 UTC, AdityaRaj23 commented
tests are fine on my side what is the issue with this debian 10 and debian 11 can you brief me about this i am not sure whats wrong...

2023-10-31 16:37 UTC, kessler-frost commented
You can see the reason why the test failed here: https://github.com/AgnostiqHQ/covalent/actions/runs/6705590122/job/18231396245?pr=1810. The failing statement is `assert named_args == [1]` whereas it should be `assert named_args == {'a': 1}` instead. This is since everything will get an appropriate name from running `get_named_params`.

2023-10-31 17:08 UTC, kessler-frost commented
@AdityaRaj23 Thanks for this, we'll get this merged now.

2023-10-31 18:06 UTC, kessler-frost commented
Thanks @AdityaRaj23 ! I'm glad you'd like to contribute more we're always looking for eager contributors like you. Please feel free to take a look at issues tagged with `good-first-issue` or `help-wanted` labels if you're interested.

2023-11-02 14:24 UTC, merged