Chore: Type fixed in `pennylane_iris_classification/source.ipynb` and  `qaoa_maxcut/source.ipynb`
AgnostiqHQ/covalent pull request #1827
Opened 2023-10-13 07:41 UTC by SusheelThapa

- [X] I have added the tests to cover my changes.
- [X] I have updated the documentation and CHANGELOG accordingly.
- [X] I have read the CONTRIBUTING document.

2023-10-13 10:10 UTC, kessler-frost commented
Hey @SusheelThapa thanks for the PR! But can you please create only one PR containing all of the typo fixes and close all the others instead? It makes things easier when reviewing and will be less work for you as well. Otherwise this looks very spammy even though that wasn't your intention. Hope you understand, thanks!

2023-10-13 10:41 UTC, SusheelThapa commented
@kessler-frost , When i try to merge the other branch into one to create, it too create unnecessary commits as shown below,
![image](https://github.com/AgnostiqHQ/covalent/assets/83917129/6cd5e3df-43ac-481b-94d2-cf0ebe781b19)

This repository is participating in hacktoberfest. And closing all the Pull Request and opening single PR again might ban me from hacktoberfest.

For next time, I will keep this in mind.

2023-10-13 10:56 UTC, kessler-frost commented
@SusheelThapa having several commits in one PR/branch is fine, having several PRs with too few changes in each is not. For the Hacktoberfest part, it is true that we are participating in that, but the only issues that are part of it are labelled as such. You can find them here if you're interested: https://github.com/AgnostiqHQ/covalent/labels/hacktoberfest.

Here's more information on what won't count towards Hacktoberfest: https://hacktoberfest.com/participation/#spam.

2023-10-13 11:06 UTC, SusheelThapa commented
@kessler-frost Can you please review it again?

2023-10-13 11:15 UTC, kessler-frost commented
Please close all the other PRs, update the title of this PR, and update the changelog. Again, just reiterating, this PR will not be counted towards Hacktoberfest due to the conditions mentioned in my earlier message, but we are thankful for your contribution.

2023-10-13 11:21 UTC, SusheelThapa commented
@kessler-frost  I have no idea how to update CHANGELOG.

2023-10-13 11:25 UTC, kessler-frost commented
You simply have to add a brief explanation in one line under the appropriate section in the `CHANGELOG.md` file. So for example, near the top of the file there's an `[UNRELEASED]` tag under which there's a `Fixed` heading, under that heading you can add that you have fixed typos in several files.

2023-10-13 11:29 UTC, SusheelThapa commented
@kessler-frost I have update CHANGELOG

2023-10-16 13:39 UTC, kessler-frost requested changes

2023-10-16 13:39 UTC, kessler-frost commented on CHANGELOG.md
You probably won't be allowed to make changes to this file apart from the things under the `[UNRELEASED]` block by the `version` check.

2023-10-16 13:39 UTC, kessler-frost commented on doc/source/getting_started/compatibility.rst
It's Big Sur here, not Big Sure.

2023-10-16 13:39 UTC, kessler-frost commented on doc/source/tutorials/1_QuantumMachineLearning/classical_quantum_svm/source.ipynb
> +    " of the SVM and QSVM models. We use the `scikit-learn` package for SVM and `qiskit_machine_learning` for QSVM implementations.\n",
Not sure why this is being split into 2 lines.

2023-10-17 14:48 UTC, SusheelThapa commented on CHANGELOG.md
I didnot get you @kessler-frost

2023-10-17 15:00 UTC, kessler-frost commented on CHANGELOG.md
So, in the changelog file, you have corrected typos in a lot of places which are outside of the `[UNRELEASED]` heading, for example the change in line 592-593 of `folder`. The scope of the unreleased heading is until the last released changelogs, so in the current case, till line 46 or until this is encountered `## [0.229.0-rc.0] - 2023-09-22`. The changes outside of the unreleased heading are not permitted by the `version` check, since the release version is automatically generated based on what's inside the `[UNRELEASED]` block.

2023-10-17 16:54 UTC, closed without merging