Allow non-string infra defaults for plugins
AgnostiqHQ/covalent pull request #1921
Opened 2024-01-29 23:36 UTC by araghukas

Fix for https://github.com/AgnostiqHQ/covalent/issues/1920

- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

2024-01-31 17:51 UTC, kessler-frost requested changes
Looks gtg apart from the changelog comment 💯 !

2024-01-31 17:51 UTC, kessler-frost commented on CHANGELOG.md
> +- Added config manager method to handle Python to TF value conversion (e.g. None->null, True->true, False->false).
config manager? Do you mean CRM?

2024-01-31 17:54 UTC, araghukas commented on CHANGELOG.md
> +- Added config manager method to handle Python to TF value conversion (e.g. None->null, True->true, False->false).
oops 🤦

2024-02-01 01:29 UTC, kessler-frost approved these changes

2024-02-01 01:29 UTC, merged