API: redesign implementation of `get_result(wait=True)`
AgnostiqHQ/covalent pull request #1949
Opened 2024-05-21 18:48 UTC by cjao

`get_result(wait=True)` will still fail after some time. The PR addresses this through a combination of API and client-side improvements.

The previous `GET /dispatches/{dispatch_id}` endpoint was trying to do too much. Its responsibilities are now separated into two endpoints:

* `GET /dispatches`: bulk query dispatch summaries (including status) with options to filter by `dispatch_id`, sort chronologically, and also limit the output to status only.

* `GET /dispatches/{dispatch_id}`: download manifest

To achieve the desired behavior of `get_result(id, wait=True)`, the client

1. Polls the dispatch status by querying the first endpoint.

2. Downloads the manifest after the dispatch has reached a final status.

The server no longer returns 503 errors when the dispatch is not yet "ready". A 503 status code is not entirely accurate here because it is intended to convey temporary service unavailablity resulting from server overload or rate limiting. However, the fact that the workflow is still running does not indicate any fault of the server.

These changes will allow `get_result(dispatch_id, wait=True)` to wait as long as required instead of erroring out after some time.

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2024-06-14 23:02 UTC, santoshkumarradha commented
@cjao can you see if you make this true in a way for other waits as well like env and deployment ?

2025-01-17 15:30 UTC, FyzHsn requested changes

2025-01-17 15:30 UTC, FyzHsn commented on covalent_dispatcher/_dal/result.py
> +    def get_toplevel_dispatches(
If this is not used, delete

2025-01-17 15:59 UTC, FyzHsn approved these changes

2025-01-17 16:28 UTC, wjcunningham7 approved these changes

2025-01-17 16:31 UTC, merged