185 object store
AgnostiqHQ/covalent pull request #197
Opened 2022-03-15 15:10 UTC by cjao

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2022-03-18 13:45 UTC, scottwn requested changes

2022-03-18 13:45 UTC, scottwn commented on refactor/data/app/api/api_v0/endpoints/fs.py
> +from minio import Minio
need to add minio in requirements

2022-03-18 15:16 UTC, cjao commented
A couple of issues to be addressed before this is merged:

- Config management: how should the user configure which StorageBackend to use (Local, Minio) and set backend-specific settings (such as AWS credentials)?
- Better logging

2022-03-24 18:48 UTC, scottwn approved these changes

2022-03-24 19:03 UTC, merged