Issue #156
AgnostiqHQ/covalent pull request #208
Opened 2022-03-20 20:45 UTC by m-chaturvedi

- [X] I have added the tests to cover my changes.
- [X] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [X] I have read the CONTRIBUTING document.

Towards #156

2022-03-20 20:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AgnostiqHQ/covalent?pullRequest=208) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AgnostiqHQ/covalent?pullRequest=208) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AgnostiqHQ/covalent?pullRequest=208) it.</sub>

2022-03-21 02:15 UTC, Emmanuel289 requested changes
Thanks for this PR. In order to be compliant with the format for Keep a Changelog, the fix should be entered as a new changelog entry with the next higher release number (0.32.5) and the current date. VERSION should also be updated to the release number.

2022-03-21 14:49 UTC, scottwn submitted a review, later dismissed
LGTM 👍 
thanks @m-chaturvedi 
fixes #156

2022-03-21 15:38 UTC, Emmanuel289 approved these changes

2022-03-21 15:39 UTC, merged