Add delete endpoint to object and results services
AgnostiqHQ/covalent pull request #271
Opened 2022-03-31 14:05 UTC by cjao

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

Closes https://github.com/AgnostiqHQ/covalent-staging/issues/432

2022-03-31 15:38 UTC, scottwn requested changes
Do you intend for this to fix the issue in #221? I think the problem will remain even after merging this

2022-03-31 15:38 UTC, scottwn commented on refactor/results/app/api/api_v0/endpoints/workflow.py
> +    sql = "DELETE FROM results WHERE dispatch_id = ?"
This should only delete from the DB if the object deletion was successful. Otherwise we will create orphaned objects.

2022-03-31 15:54 UTC, cjao commented
> Do you intend for this to fix the issue in #221? I think the problem will remain even after merging this

#272 would fix #221 unless you see some problem with that approach.

2022-04-04 11:37 UTC, cjao commented
Any more changes needed?

2022-04-04 14:59 UTC, scottwn approved these changes

2022-04-04 15:11 UTC, merged