Supervisord NATS integration
AgnostiqHQ/covalent pull request #338
Opened 2022-04-08 21:55 UTC by AlejandroEsquivel

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2022-04-09 14:26 UTC, FyzHsn requested changes
@AlejandroEsquivel I just pulled this branch in and started supervisord via `covalent start --refactor`. Then I ran `python example_dispatch.py`. I found that the file did not run. But the moment I run `nats-server` in another terminal the workflow dispatches. At least on my machine, these changes don't seem to be starting up the nats-server

2022-04-11 17:46 UTC, AlejandroEsquivel commented
> @AlejandroEsquivel I just pulled this branch in and started supervisord via `covalent start --refactor`. Then I ran `python example_dispatch.py`. I found that the file did not run. But the moment I run `nats-server` in another terminal the workflow dispatches. At least on my machine, these changes don't seem to be starting up the nats-server

@FyzHsn I can't seem to reproduce, is it possible to provide logs of the NATS process? (via supervisord dashboard or `covalent logs -s nats -l 8000`). It is likely NATS is unable to start but not too sure why that would be the case if port 4200 is not occupied.

2022-04-11 18:57 UTC, FyzHsn commented
> > @AlejandroEsquivel I just pulled this branch in and started supervisord via `covalent start --refactor`. Then I ran `python example_dispatch.py`. I found that the file did not run. But the moment I run `nats-server` in another terminal the workflow dispatches. At least on my machine, these changes don't seem to be starting up the nats-server
> 
> @FyzHsn I can't seem to reproduce, is it possible to provide logs of the NATS process? (via supervisord dashboard or `covalent logs -s nats -l 8000`). It is likely NATS is unable to start but not too sure why that would be the case if port 4200 is not occupied.

I just tried the same steps after doing `covalent purge`. Now everything works. My bad. This is ready ter go!

2022-04-11 18:58 UTC, FyzHsn approved these changes

2022-04-11 19:11 UTC, merged