Updated the `choosing_conda_environment` howto.
AgnostiqHQ/covalent pull request #400
Opened 2022-04-18 20:50 UTC by jkanem

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2022-04-18 20:52 UTC, jkanem commented
Here are the how-to notebooks which need checking:
- - [ ] collection
- - - [ ] query_electron_execution_result
- - - [ ] query_lattice_execution_result
- - - [ ] query_multiple_lattice_execution_results
- - [ ] config
- - - [ ] customization
- - [ ] execution
- - - [ ] cancel_dispatch
- - - [ ] choosing_conda_environments
- - - [ ] choosing_executors
- - - [x] creating_custom_executors
- - - [ ] execute_individual_electron
- - - [ ] execute_lattice
- - - [ ] execute_multiple_lattices
- - - [ ] execute_sublattice
- - - [ ] synchronize_lattice
- - [ ] orchestration
- - - [ ] add_constraints_to_lattice
- - - [ ] add_electron_to_lattice
- - - [ ] construct_c_task
- - - [ ] construct_electron
- - - [ ] construct_lattice
- - - [ ] construct_lepton
- - - [ ] visualize_lattice
- - [ ] status
- - - [ ] query_electron_execution_status
- - - [ ] query_lattice_execution_status
- - - [ ] query_lattice_execution_time

2022-04-18 20:54 UTC, jkanem commented
Fixes https://github.com/AgnostiqHQ/covalent-staging/issues/460

2022-04-20 14:32 UTC, scottwn requested changes

2022-04-20 14:32 UTC, scottwn commented on doc/source/how_to/execution/choosing_conda_environments.ipynb
> +    ".. note:: Ensure that the covalent server has been started properly before attempting to execute the lattice."
```suggestion
    ".. note:: Ensure that Covalent services have been started properly before attempting to execute the lattice."
```

2022-04-20 14:32 UTC, scottwn commented on doc/source/how_to/execution/choosing_executors.ipynb
> +    ".. note:: Ensure that the covalent server has been started properly before attempting to execute the lattice."
```suggestion
    ".. note:: Ensure that Covalent services have been started properly before attempting to execute the lattice."
```

2022-04-20 14:32 UTC, scottwn commented on doc/source/how_to/execution/execute_individual_electron.ipynb
> +    ".. note:: Ensure that the covalent server has been started properly before attempting to execute the lattice."
```suggestion
    ".. note:: Ensure that Covalent services have been started properly before attempting to execute the lattice."
```

2022-04-20 14:32 UTC, scottwn commented on doc/source/how_to/execution/execute_lattice.ipynb
> +    ".. note:: Ensure that Covalent has been started before attempting to execute the lattice."
```suggestion
    ".. note:: Ensure that Covalent services have been started before attempting to execute the lattice."
```

2022-04-20 15:29 UTC, jkanem commented on doc/source/how_to/execution/choosing_conda_environments.ipynb
> +    ".. note:: Ensure that the covalent server has been started properly before attempting to execute the lattice."
Fixed

2022-04-20 15:29 UTC, jkanem commented on doc/source/how_to/execution/execute_lattice.ipynb
> +    ".. note:: Ensure that Covalent has been started before attempting to execute the lattice."
Fixed

2022-04-20 17:55 UTC, merged