Issue #30 (#367)
AgnostiqHQ/covalent pull request #558
Opened 2022-05-24 13:22 UTC by scottwn

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2022-05-24 16:30 UTC, scottwn commented
@venkatBala I'm handing this off to you to merge if you want.

2022-05-25 03:11 UTC, wjcunningham7 requested changes

2022-05-25 03:11 UTC, wjcunningham7 commented on .github/workflows/tests.yml
> -          PYTHONPATH=$PWD/covalent_dispatcher pytest covalent_dispatcher -vv --cov=covalent_dispatcher --cov-config=.coveragerc
probably we want to keep the one for the dispatcher

2022-05-25 17:24 UTC, wjcunningham7 approved these changes

2022-05-25 17:24 UTC, merged