Adding `wait_for` support
AgnostiqHQ/covalent pull request #753
Opened 2022-06-30 14:04 UTC by kessler-frost

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

Resolves #713.

2022-07-05 21:57 UTC, AlejandroEsquivel requested changes

2022-07-06 13:43 UTC, santoshkumarradha commented on covalent/_workflow/electron.py
> +                with open("mafile.txt", "a") as f:
😆

2022-07-06 15:19 UTC, kessler-frost commented on covalent/_workflow/electron.py
> +                with open("mafile.txt", "a") as f:
🥲 It wasn't intended to be here. Changing now.

2022-07-06 15:19 UTC, kessler-frost commented on covalent/_workflow/electron.py
> +                edge_name="!waiting_edge",
Yeah, I agree, will do.

2022-07-06 20:24 UTC, AlejandroEsquivel commented
@kessler-frost if documentation will be included in the PR - maybe change back to draft and mark as ready when done?

2022-07-07 19:57 UTC, AlejandroEsquivel approved these changes
Looks good @kessler-frost 👍

2022-07-12 16:37 UTC, AlejandroEsquivel submitted a review, later dismissed

2022-07-12 16:38 UTC, AlejandroEsquivel approved these changes

2022-07-12 16:58 UTC, merged